global using System;
global using MongoDB.Entities;
global using SharedService.Filters;
global using SharedService.Exceptions;
global using SharedService.Endpoints;
global using SharedService.Extensions;
global using SearchService.Models;
global using MongoDB.Driver;
global using SearchService.Data;
