import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getCurrentUser } from "../features/auth/actions/auth-action";
import StoreProvider from "./redux";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StockEase",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
